# Generated by Django 3.0.5 on 2020-04-25 10:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc

import csv
import linecache

def load_game(apps, schema_editor):

    Sentence = apps.get_model("game", "Sentence")

    #path_to_data = "/home/tony/Desktop/491/kanarya/game_project/game/static/game/sentences.csv"
    path_to_data = "../static/game/sentences.csv"

    f = open(path_to_data, 'r')

    for idx, line in enumerate(f):

        index = list(csv.reader([line]))[0][0]
        text = list(csv.reader([line]))[0][1]
        pos = int(list(csv.reader([line]))[0][2])   

        sentence_info = {
            'sentence_idx': index,
            'full_sentence': text,
            'pos': pos
        }

        print("Sentence " + str(index) + " is inserted into the database. ")
        status = get_status(sentence_info)
        clitic = get_clitic(sentence_info)

        instance = Sentence(index=index,
                            text=text,
                            pos=pos,
                            status=status,
                            clitic=clitic)
        instance.save()


def delete_game(apps, schema_editor):
    Sentence = apps.get_model("game", "Sentence")
    Sentence.objects.all().delete()

def get_clitic(sentence_info):

    full_sentence = sentence_info['full_sentence']
    pos = sentence_info['pos']

    words = full_sentence.split()

    word_deda = words[pos]

    return word_deda[-2:]

# Returns if the deda is separate or adjacent
def get_status(sentence_info):

    full_sentence = sentence_info['full_sentence']
    pos = sentence_info['pos']
    
    words = full_sentence.split()

    # if separate
    if len(words[pos]) == 2:
        return "SEPARATE"
    else:
        return "ADJACENT"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('text', models.TextField()),
                ('pos', models.IntegerField()),
                ('status', models.TextField()),
                ('clitic', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Sentence'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 4, 25, 10, 12, 14, 710261, tzinfo=utc))),
                ('name', models.CharField(max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Question')),
            ],
        ),
        migrations.RunPython(load_game,delete_game),
    ]
