# Generated by Django 3.0.5 on 2020-04-25 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200425_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 10, 34, 56, 783009, tzinfo=utc)),
        ),
    ]
