# Generated by Django 3.0.5 on 2020-05-02 20:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200502_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='relative_mask_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 20, 15, 25, 531687, tzinfo=utc)),
        ),
    ]
