# Generated by Django 3.0.5 on 2020-05-09 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200502_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='relative_unmask_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 19, 34, 17, 693182, tzinfo=utc)),
        ),
    ]
