# Generated by Django 3.0.5 on 2020-05-10 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200509_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hint_count',
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 17, 58, 25, 703196, tzinfo=utc)),
        ),
    ]
