# Generated by Django 3.0.5 on 2020-05-21 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200510_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 25, 49, 573595, tzinfo=utc)),
        ),
    ]
