# Generated by Django 3.0.5 on 2020-05-21 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20200521_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 19, 8, 43, 251926, tzinfo=utc)),
        ),
    ]
