# Generated by Django 3.0.5 on 2020-05-24 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20200521_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 11, 21, 53, 188267, tzinfo=utc)),
        ),
    ]
