# Generated by Django 3.0.5 on 2020-05-24 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20200524_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProficiencySentence',
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 11, 31, 14, 233635, tzinfo=utc)),
        ),
    ]
