# Generated by Django 3.0.5 on 2020-05-24 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20200524_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 12, 7, 17, 168444, tzinfo=utc)),
        ),
    ]
