# Generated by Django 3.0.5 on 2020-05-27 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20200524_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 18, 23, 20, 465829, tzinfo=utc)),
        ),
    ]
