# Generated by Django 3.0.5 on 2020-05-31 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20200527_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 9, 0, 59, 316872, tzinfo=utc)),
        ),
    ]
