# Generated by Django 3.0.5 on 2020-07-30 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20200620_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 19, 13, 40, 289601, tzinfo=utc)),
        ),
    ]
