# Generated by Django 3.0.5 on 2020-07-31 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20200730_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 13, 30, 4, 504656, tzinfo=utc)),
        ),
    ]
