# Generated by Django 3.0.5 on 2020-07-31 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20200731_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
