# Generated by Django 3.0.5 on 2020-06-06 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20200606_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 17, 24, 42, 343724, tzinfo=utc)),
        ),
    ]
