# Generated by Django 3.0.5 on 2020-06-07 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20200606_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 19, 22, 34, 82105, tzinfo=utc)),
        ),
    ]
