# Generated by Django 3.0.5 on 2020-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='correct_answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
