# Generated by Django 3.0.5 on 2020-04-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200425_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_seen_sentence',
            new_name='last_seen_sentence_idx',
        ),
    ]
