# Generated by Django 3.0.5 on 2020-05-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200425_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onam',
            field=models.BooleanField(default=False),
        ),
    ]
