# Generated by Django 3.0.5 on 2020-05-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_onam'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isOnamSubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
