# Generated by Django 3.0.5 on 2020-05-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200524_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tos',
            field=models.BooleanField(default=False),
        ),
    ]
