# Generated by Django 3.0.5 on 2020-05-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_tos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isOnamSubmitted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='onam',
        ),
    ]
