# Generated by Django 3.0.5 on 2020-06-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200527_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen_warmup_idx',
            field=models.IntegerField(default=1),
        ),
    ]
