# Generated by Django 3.0.5 on 2020-06-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_last_seen_warmup_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_warmup_done',
            field=models.BooleanField(default=False),
        ),
    ]
