# Generated by Django 3.0.5 on 2020-06-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_is_warmup_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_prof_done',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_seen_prof_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prof_score',
        ),
    ]
