# Generated by Django 3.0.5 on 2020-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellchecker', '0004_auto_20200531_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='tagged_sentence',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='query',
            name='sentence',
            field=models.TextField(default=''),
        ),
    ]
