# Generated by Django 3.0.5 on 2020-07-31 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellchecker', '0005_auto_20200730_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spellchecker.Query')),
            ],
        ),
    ]
