# Generated by Django 3.0.5 on 2020-07-31 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spellchecker', '0006_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='isHappy',
        ),
        migrations.AddField(
            model_name='query',
            name='random_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
